version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - epub
  - pdf

python:
   install:
      - method: pip
        path: .
        extra_requirements:
           - docs

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_checkout:
      - git fetch --depth 1000
    pre_install:
      - git update-index --assume-unchanged docs/conf.py
      - pip install setuptools==62.4.0 setuptools_scm[toml]==6.4.2
