dist: xenial
sudo: false
language: python
matrix:
  include:
    - python: 3.7
      env: TOXENV=check
    - python: 3.7
      env: TOXENV=docs
    - python: 3.6
      env:
        TOXENV=py36
        PYTEST_ADDOPTS="--remote-data"

install: pip install tox-travis

script: tox

