name: Document error
description: File a document error report.
title: "[Docs]: "
labels: ["documents", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this document error report or suggestion!
  - type: textarea
    id: description
    attributes:
      label: document error or request
      description: A clear and concise description of what the error is.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed change
      description: A clear and concise description of what you want to see.
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
